name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.24
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_activity: yes
          plugin_habits: yes
          plugin_habits_facts: yes
#          plugin_achievements: yes
#          plugin_anilist: yes
#          plugin_anilist_sections: favorites,watching,reading
#          plugin_anilist_user: pfuenzle
